"use client"
import React, { useState } from "react";
import {
  Accordion,
  AccordionSummary,
  AccordionDetails,
} from "@mui/material";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import styled from "styled-components";

const faqs = [
  {
    question: "Is solar power safe?",
    answer:
      "Yes. The electricity produced by a solar power system is no different than the electricity you get from your electricity distribution company. The only difference is the source. Moreover, it is among the safest sources of electricity consumption because it is neither hazardous nor does it release any toxic or harmful gases during production.",
  },
  {
    question: "What are the different types of Solar systems?",
    answer: "There are three main types: On-grid, Off-grid, and Hybrid systems.",
  },
  {
    question: "What is Net metering?",
    answer:
      "Net metering allows you to send excess electricity generated by your solar panels back to the grid in exchange for credits on your electricity bill.",
  },
  {
    question: "What is the life of a rooftop solar system?",
    answer: "A rooftop solar system typically lasts 25-30 years with proper maintenance.",
  },
  {
    question: "What is the break-even period for Solar rooftop projects?",
    answer: "The break-even period typically ranges from 5 to 7 years depending on system size and local electricity rates.",
  },
];

const FAQSection: React.FC = () => {
  const [expanded, setExpanded] = useState<string | false>(false);

  const handleChange =
    (panel: string) => (_: React.SyntheticEvent, isExpanded: boolean) => {
      setExpanded(isExpanded ? panel : false);
    };

  return (
    <Container>
      <Title>FAQs</Title>
      <FAQContainer>
        {faqs.map((faq, index) => (
          <StyledAccordion
            key={index}
            expanded={expanded === `panel${index}`}
            onChange={handleChange(`panel${index}`)}
          >
            <AccordionSummary expandIcon={<StyledExpandMoreIcon />}>
              <p>
                {faq.question}
              </p>
            </AccordionSummary>
            <AccordionDetails>
              <AnswerText>{faq.answer}</AnswerText>
            </AccordionDetails>
          </StyledAccordion>
        ))}
      </FAQContainer>
    </Container>
  );
};

export default FAQSection;


const Container = styled.div`
  width: 80%;
  margin: auto;
  padding: 50px 0;
  font-family:${(props)=>props.theme.fontFamily};
  margin-bottom:80px;
`;

const Title = styled.h2`
  text-align: center;
  font-weight: 600;
  margin-bottom: 20px;
`;

const FAQContainer = styled.div`
  display: flex;
  flex-direction: column;
  gap: 15px;
`;

const StyledAccordion = styled(Accordion)`
  && {
    border-radius: 10px;
    box-shadow: none;
    background: #EFEFEF;
    &:before {
      display: none;
    }
      p{
      margin:0;
      padding:0;
      font-size:15px;
      font-weight:600;
      }
  }
`;

const StyledExpandMoreIcon = styled(ExpandMoreIcon)`
  && {
    width: 25px; 
    height: 25px;
    font-size: 24px; 
    border-radius: 50%;
    background-color: ${(props) => props.theme.buttons.secondaryBackground};
    color: ${(props) => props.theme.colors.secondaryText};
    display: flex;
    align-items: center;
    justify-content: center;
  }
`;
const AnswerText = styled.p`
&&{
margin:0;
padding:0;
font-size:10px;
color:${(props)=>props.theme.colors.lightText};
}
`;